_commit: 1.3.0-16-gaf84857
_src_path: https://github.com/flowtaleai/copier-python-poetry
author_email: simgunz@gmail.com
author_name: Simone Gaiarin
distribution_name: mealie-curator
generate_dockerfile: false
generate_docs: none
generate_example_code: false
git_hosting: none
ide: vscode
license: MIT license
max_line_length: 88
package_name: mealiecurator
package_type: cli
project_name: Mealie Curator
project_short_description: 'Command-line toolkit for maintaining and organizing your
    Mealie recipe database

    '
python_version: '3.12'
testing_framework: pytest
use_flake8_strict_plugins: true
use_jupyter_notebooks: false
version: 0.0.0
